name: Deploy to EC2 Static

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the `main` branch
  workflow_dispatch:  # Enable manual trigger from the GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version

      # Step 3: Install dependencies and build the app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Compress the build files
      - name: Archive build files
        run: tar -czf dist.tar.gz dist/

      # Step 5: Deploy to EC2 using SCP
      - name: Deploy to EC2
        uses: appleboy/scp-action@master # Use the latest version
        with:
          host: ${{ secrets.EC2_HOST }}      # Add EC2 public IP in GitHub Secrets
          username: ubuntu                  # Your EC2 username
          key: ${{ secrets.EC2_PRIVATE_KEY }} # Add private key in GitHub Secrets
          port: 22                          # Default SSH port
          source: dist.tar.gz
          target: /home/ubuntu/

      # Step 6: Extract and move files to Nginx directory using SSH
      - name: Extract and move files
        uses: appleboy/ssh-action@master # Use the latest version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/html/*
            sudo tar -xzf /home/ubuntu/dist.tar.gz -C /var/www/html/
            sudo systemctl restart nginx
