name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the `main` branch
  workflow_dispatch:  # Enable manual deployment trigger from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies and build the app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Compress the build files
      - name: Archive build files
        run: tar -czf dist.tar.gz dist/

      # Step 5: Deploy to EC2 using SCP
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: dist.tar.gz
          target: /home/ubuntu/

      # Step 6: Extract and move contents to Nginx directory using SSH
      - name: Extract and move files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            # Remove existing files in /var/www/html
            sudo rm -rf /var/www/html/*
            
            # Extract the dist.tar.gz archive
            sudo tar -xzf /home/ubuntu/dist.tar.gz -C /home/ubuntu/
            
            # Move contents of 'dist' to /var/www/html
            sudo mv /home/ubuntu/dist/* /var/www/html/
            
            # Move hidden files (if any)
            sudo mv /home/ubuntu/dist/.[^.]* /var/www/html/ 2>/dev/null || true
            
            # Clean up temporary files
            sudo rm -rf /home/ubuntu/dist /home/ubuntu/dist.tar.gz
            
            # Restart Nginx to apply changes
            sudo systemctl restart nginx
